### ISSUE TITLE
Request for all files committed by me, Relms12345, to be removed immediately.

### ISSUE THREAD

**Issue by Relms12345** [wynterfurrybot/wynter#3]
To whom it may concern, I request that commits and all files committed by me, Relms12345, on this git repository, wynterfurrybot/wynter, be removed within a week of this notice. Failure to do so will result in further actions taken. 

Relms

Edit: You however may be allowed to edit existing code that has been written by me.

**Comment by Nanofaux** [comment]
Perhaps you should be careful of how you license the bot, eh?
![image](https://user-images.githubusercontent.com/62013808/101021185-942a2800-353d-11eb-8678-52b53e043278.png)

**Comment by Nanofaux** [comment]
![image](https://user-images.githubusercontent.com/62013808/101021300-bfad1280-353d-11eb-8e9d-eb92a702e820.png)

**Comment by Nanofaux** [comment]
Any and all work you published to this repository was, unless explicitly stated by you in the commit/code, surrendered to the Creative Commons - Attribution license.

**Comment by Relms12345** [comment]
Ok want me to explicitly state all code ive written myself? I'd gladly do so :D
